#!/usr/bin/env python3
"""
Generates 301 redirects from extensionless URLs to their .html canonical.

Why this is needed: the host serves both /about and /about.html with a 200,
so Google discovers and crawls each page twice. The canonical tag means the
right version gets indexed, but the duplicate still consumes a crawl and shows
up in Search Console as "Alternate page with proper canonical tag". At 78 pages
that is untidy; at 250 it is a real waste.

Why this is safe HERE but would not be everywhere: some hosts do the opposite,
redirecting /about.html to /about. If that were happening, adding these rules
would create an infinite loop and take the site down. It is not happening on
this site - Search Console has crawled BOTH forms of the same page and
classified each with a 200-level status, which is only possible if neither
redirects. Rules are written for exact paths rather than a /* wildcard, so a
request for /about.html matches nothing and is served directly.

Run after adding pages:  python3 build-redirects.py
"""
import pathlib, re, sys

SITE = pathlib.Path(__file__).resolve().parent
TOML = SITE / 'netlify.toml'
START = '# --- BEGIN generated extensionless redirects ---'
END = '# --- END generated extensionless redirects ---'

SKIP = {'404.html', 'google9a6ccbbe2c218671.html', 'index.html'}


def main():
    text = TOML.read_text(encoding='utf-8')

    # Never generate a rule for a path already handled by a hand-written one.
    existing = set(re.findall(r'from\s*=\s*"([^"]+)"', text.split(START)[0]))

    rules = []
    for p in sorted(SITE.glob('*.html')):
        if p.name in SKIP:
            continue
        bare = '/' + p.stem
        if bare in existing or ('/' + p.name) in existing:
            continue
        rules.append((bare, '/' + p.name))

    block = [START,
             '# Generated by build-redirects.py - do not edit by hand.',
             '# Collapses /page to /page.html so each page has exactly one crawlable URL.',
             '# Safe because nothing on this site redirects .html to extensionless;',
             '# if that ever changes, DELETE this block first or you will create a loop.']
    for bare, target in rules:
        block += ['', '[[redirects]]',
                  f'  from = "{bare}"',
                  f'  to = "{target}"',
                  '  status = 301',
                  '  force = true']
    block += ['', END]
    generated = '\n'.join(block) + '\n'

    if START in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        text = head + generated + tail
    else:
        # must sit BEFORE the catch-all 404 rule, which matches everything
        marker = '[[redirects]]\n  from = "/*"'
        if marker in text:
            i = text.index(marker)
            text = text[:i] + generated + '\n' + text[i:]
        else:
            text = text.rstrip() + '\n\n' + generated

    TOML.write_text(text, encoding='utf-8')
    print(f'{len(rules)} extensionless redirects generated')

    # --- loop check --------------------------------------------------------
    froms = {}
    for m in re.finditer(r'\[\[redirects\]\]\s*\n\s*from\s*=\s*"([^"]+)"\s*\n\s*to\s*=\s*"([^"]+)"', text):
        froms[m.group(1)] = m.group(2)
    loops = [f'{a} -> {b}' for a, b in froms.items()
             if b in froms and froms[b] != b and not b.startswith('http')]
    if loops:
        print('  !! POSSIBLE LOOP:', loops)
        return 1
    print('  loop check: no redirect target is itself redirected')
    return 0


if __name__ == '__main__':
    sys.exit(main())
